export function generateReadmeContent(description: string, _deploymentName: string | null) {
  return `# ${description}

This project was generated by an AI coding agent.

## Project structure

- \`src/\` — frontend source code (React + Vite)
- \`convex/\` — backend functions and schema

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Deploying

Run \`npm run build\` to build for production, then deploy the \`dist/\` folder to any static host.
`;
}
